-- Walkin SQLite schema
-- Ported from supabase/migrations/0001_initial_schema.sql.
-- UUIDs are TEXT generated by the application layer.
-- Postgres arrays (text[], uuid[]) are stored as JSON-encoded TEXT.
-- Postgres jsonb is stored as JSON-encoded TEXT.
-- RLS policies and auth.users references are removed (no auth layer yet).

CREATE TABLE IF NOT EXISTS profiles (
    id           TEXT PRIMARY KEY,
    display_name TEXT,
    avatar_url   TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE IF NOT EXISTS closet_items (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    category    TEXT NOT NULL CHECK (category IN ('top', 'bottom', 'dress', 'outerwear', 'shoe', 'accessory', 'other')),
    image_path  TEXT NOT NULL,
    colors      TEXT NOT NULL DEFAULT '[]',
    notes       TEXT,
    tags        TEXT NOT NULL DEFAULT '[]',
    ai_metadata TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE IF NOT EXISTS inspiration_sources (
    id               TEXT PRIMARY KEY,
    user_id          TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    type             TEXT NOT NULL CHECK (type IN ('pinterest_board', 'image_upload', 'manual_note')),
    source_url       TEXT,
    image_path       TEXT,
    extracted_themes TEXT NOT NULL DEFAULT '[]',
    ai_summary       TEXT,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE IF NOT EXISTS style_profiles (
    user_id          TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    themes           TEXT NOT NULL DEFAULT '[]',
    preferred_colors TEXT NOT NULL DEFAULT '[]',
    avoided_items    TEXT NOT NULL DEFAULT '[]',
    occasions        TEXT NOT NULL DEFAULT '[]',
    notes            TEXT,
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE IF NOT EXISTS outfits (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    closet_item_ids TEXT NOT NULL DEFAULT '[]',
    styling_notes   TEXT NOT NULL,
    occasions       TEXT NOT NULL DEFAULT '[]',
    saved           INTEGER NOT NULL DEFAULT 0,
    ai_rationale    TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
